### ISSUE TITLE
Add "relationships" key

### ISSUE THREAD

**Issue by mrcasals** [fotinakis/jsonapi-serializers#1]
It seems like JSON API got updated and replaced the `"links` key by a `"relationships"` key:

```json
  "data": [{
    "type": "posts",
    "id": "1",
    "attributes": {
      "title": "JSON API paints my bikeshed!"
    },
    "relationships": {
      "author": {
        "links": {
          "self": "http://example.com/posts/1/relationships/author",
          "related": "http://example.com/posts/1/author"
        },
        "linkage": { "type": "people", "id": "9" }
      },
      "comments": {
        "links": {
          "self": "http://example.com/posts/1/relationships/comments",
          "related": "http://example.com/posts/1/comments"
        },
        "linkage": [
          { "type": "comments", "id": "5" },
          { "type": "comments", "id": "12" }
        ]
      }
    },
    "links": {
      "self": "http://example.com/posts/1"
    }
  }
```

**Comment by fotinakis** [comment]
Huh, looks like a lot of things changed, there's now a top-level `links` key too (http://jsonapi.org/format/#fetching-resources-responses). Can't wait for this to stabilize :), and also I need to find a real changelog to keep up with the changes.

For this issue, I'll fix this up in the next few days. If you want, just renaming `links` to `relationships` would be a pretty easy change and I'd be happy to accept a PR, there are good tests for everything.

**Comment by mrcasals** [comment]
Seems like not only a renaming is needed: there'e still a `"links"` section with the `"self"` link. The others have been moved to `"relationships"`.

As for the Changelog, I guess the only one available is the commits log on their repo: https://github.com/json-api/json-api

**Comment by mrcasals** [comment]
Seems like next week (May 28th) they will release the first stable version
of the standard, so we can start working on implementing the standard here
by then :)

**Comment by fotinakis** [comment]
Yup! I think this is basically up to date with all of the spec, except for supporting the new top-level `links` (which are optional and maybe only important when there is null primary data).

I'll probably release a v1.0.0 of this gem when the spec is finalized and I'm sure that this is compliant.
