### ISSUE TITLE
Passing number to id fails on empty? 

### ISSUE THREAD

**Issue by uhrohraggy** [fotinakis/jsonapi-serializers#107]
Regarding https://github.com/fotinakis/jsonapi-serializers/blob/master/lib/jsonapi-serializers/serializer.rb#L413

if you override and pass a numeric id to the serializer, it fails on the ! empty? 
"undefined method `empty?' for 1234:Fixnum"

I think it should be written simply as:
`data['id'] = serializer.id.to_s if serializer.id.present?`

I bring it up as an issue in case I don't fully understand the context of why it was checked against  `!serializer.id.empty?`

**Comment by fotinakis** [comment]
`present?` is a Rails construct, not available to us here. A fix for this could be:

```
data['id'] = serializer.id.to_s if serializer.id && !serializer.id.to_s.empty?
```

**Comment by uhrohraggy** [comment]
thanks @fotinakis for the clarification! I thought something like that might be the case. I agree, I fixed it by calling to_s in the method definition that overrode id. Closing
