### ISSUE TITLE
[HELP] Adding relationship and link without having the relation on the model

### ISSUE THREAD

**Issue by ziggurat** [fotinakis/jsonapi-serializers#11]
Hi, let's say I have an User model and then the User have many Invitations. My issue is that in my actual User object I don't have a invitations method. Is there anyway I can add both resources (user and invitations) to the same JSON response without having to create some kind of "UserPresenter" object containing the collection?

Thanks in advance and keep up the EXCELENT work!

**Comment by fotinakis** [comment]
Yup this is supported just wasn't documented well. I updated the README to show how to do custom has_one and has_many blocks, check it out: https://github.com/fotinakis/jsonapi-serializers#custom-attributes

Thanks and glad this is useful for you!

**Comment by ziggurat** [comment]
Hi. Thanks for your reply. I have to say I don't like that approach as it seems you are directly calling the DB queries (ActiveRecord in this case) from the (almost) view part of your app. I am not using ActiveRecord in my project and I don't think it's a nice idea to put a repository call in the serializer.

**Comment by fotinakis** [comment]
That's just an example, you can extract the logic however you want, use a scope on the model or a service object or whatever, just showing you how to add stuff to the serializer which doesn't exist on the model, which answers your question.
