### ISSUE TITLE
uninitialized constant HashSerializer

### ISSUE THREAD

**Issue by chrisvel** [fotinakis/jsonapi-serializers#111]
No matter what I do, I get this error. 

```
NameError at /api/posts
uninitialized constant HashSerializer
```

I've followed the example for Sinatra. Any ideas what might be the issue ?

**Comment by mwpastore** [comment]
The object(s) you're passing to JSONAPI::Serializer.serialize are Hash object(s), so it's looking for a HashSerializer. Are you using an ORM?

**Comment by chrisvel** [comment]
hmm well I am using Sequel and sqlite3 and it returns an array of hashes. It makes sense because If I use .to_json I get an error about `Attempted to serialize a single object as a collection`.

**Comment by mwpastore** [comment]
No, Post.all returns an array of Sequel::Model instances.

**Comment by chrisvel** [comment]
Because it's inherited from Sequel::Model, I see.

**Comment by chrisvel** [comment]
I believe I must change the whole structure of my code - include models and reference to serializers from there, then try again with JSON Api.
