### ISSUE TITLE
Is there a way to set options on an included object serializer

### ISSUE THREAD

**Issue by simonv3** [fotinakis/jsonapi-serializers#13]
There might be a better way to achieve this, but here's what I have in mind:

An article includes a user, but it should only include details of the user to a limited degree, unless the user is the `current_user` at the moment, at which point it should reveal a bunch more attributes.

It's possible to do this on the directly accessed serializer because context can get passed through options, so `current_user` can get passed along. However, when they're `included`, the context [doesn't get passed through](https://github.com/fotinakis/jsonapi-serializers/blob/master/lib/jsonapi-serializers/serializer.rb#L282) it looks like. 

Does that make sense? Am I going about this the wrong way?

**Comment by fotinakis** [comment]
Yup you're thinking of it correctly, "context" is how I would solve that. I have a note in the "Unfinished Business" section of the readme that says "Support for passing context through to serializers is partially complete, but needs more work" and this is exactly the situation I imagine it would be useful for.

I can't remember exactly why, but as I remember it's not as simple as just adding it to the passthrough_options in that line you linked. Feel like attempting a PR and test for this and seeing if it works or is more complicated?

**Comment by fotinakis** [comment]
Closing this old issue, feel free to re-open.
