### ISSUE TITLE
Plain serializers for non-standard data.

### ISSUE THREAD

**Issue by fbernier** [fotinakis/jsonapi-serializers#20]
Hey,

I am using jsonapi-serializers to serializers some Elasticsearch results. The resulting object is a bit weird and non-standard and I am in a situation where I would want to have a serializer which wraps other serializers as attributes. Unfortunately, if I do this right now, I am stuck with "id", "type" keys which I don't want and all my attributes under an "attributes" key.

I was wondering if you could consider having a kind of plain serializer class, which simply serializes the data "as-is" without adding those unwanted keys (in my case).

If you have another idea, please tell me! If mine makes sense, I could be willing to try to implement it.

Thanks!

**Comment by fotinakis** [comment]
Can you show me an example of what you're doing? I have some thoughts about a cleaned up v2 of jsonapi-serializers which might be able to accomplish that.

**Comment by fotinakis** [comment]
@fbernier friendly ping here.

**Comment by fotinakis** [comment]
Closing for now, feel free to re-open.
