### ISSUE TITLE
Default options in serializer

### ISSUE THREAD

**Issue by mwpastore** [fotinakis/jsonapi-serializers#27]
Is there a way to set default options for a serializer? e.g. set `:skip_collection_check => true` in my base serializer class?

**Comment by fotinakis** [comment]
The recommended method is to define a `serialize_model` and `serialize_models` method in your base controller class, which can always pass default options.

See the https://github.com/fotinakis/jsonapi-serializers#rails-example for example.

**Comment by mwpastore** [comment]
Thanks for the quick response. What if I'm not using Rails and don't have controllers? :-)

**Comment by mwpastore** [comment]
I wrote some helpers. Ignore me. Thank you!
