### ISSUE TITLE
underscored attribute is not a valid include

### ISSUE THREAD

**Issue by SeyZ** [fotinakis/jsonapi-serializers#36]
Hey @fotinakis ! Since the 0.3.1 version, I don't understand this line (0.3.0 behavior worked well)
https://github.com/fotinakis/jsonapi-serializers/blob/master/lib/jsonapi-serializers/serializer.rb#L384

Why do you throw an error when the attribute name includes a `_` character?

**Comment by fotinakis** [comment]
This is intentional, by default you should be using a "-" instead of an underscore or else it was silently failing. See https://github.com/fotinakis/jsonapi-serializers/pull/32
