### ISSUE TITLE
Accessing model object and overriding attributes

### ISSUE THREAD

**Issue by hspazio** [fotinakis/jsonapi-serializers#43]
Hello,
Is it possible to either override the value of an attribute or define an attribute in the Serializer?
I'm also looking at ways of accessing the model object from the serializer class, for example ActiveModel::Serializer uses `object`, JSONAPI::Resource uses `@model`.

Thank you!

```ruby
class PostSerializer
  include JSONAPI::Serializer

  attributes :title, :text, :word_count

  def word_count
    # ..calculate word count here
  end
end
```

**Comment by aars** [comment]
https://github.com/fotinakis/jsonapi-serializers#custom-attributes

**Comment by hspazio** [comment]
Thank you @aars! didn't see that.
