### ISSUE TITLE
Exclude the `attributes` member when there are none

### ISSUE THREAD

**Issue by camjackson** [fotinakis/jsonapi-serializers#45]
The JSON API spec says that resource objects **MAY** (not MUST) have an `attributes` member: [reference](http://jsonapi.org/format/#document-resource-objects).

I have a serializer class with no attributes specified, and the generated hash has `"attributes" => {},`. Is there a way / could there be an option added, to totally exclude `attributes`, rather than have it present, but empty?

**Comment by camjackson** [comment]
Related: Is there a way to totally exclude the `links` member, which is also optional according to the spec?

**Comment by fotinakis** [comment]
Sorry that's actually a regression, fixed by https://github.com/fotinakis/jsonapi-serializers/commit/1e404607eb5b310fc8fa09e5f3729539caeb5757 and https://github.com/fotinakis/jsonapi-serializers/commit/37b0a0ba32b6e15061f2c5d56fbe0135d987b84c, and released in v0.6.5.

**Comment by camjackson** [comment]
Thanks @fotinakis!
