### ISSUE TITLE
Include type and id for relationship, without full resource include

### ISSUE THREAD

**Issue by camjackson** [fotinakis/jsonapi-serializers#46]
In my response, I want to include relationship information in the main resource, but I don't want to include the whole resource in the `"included"` section, mostly because the other resource has no attributes, so it's redundant.

I.e., I want to generate a response that looks like the following:

````json
{
    "data": {
        "id": "5",
        "type": "things",
        "attributes": {
            "name": "A Thing",
        },
        "links": {
            "self": "/things/5"
        },
        "relationships": {
            "otherThing": {
                "data": {
                    "type": "otherThings",
                    "id": "123"
                }
            }
        }
    }
}
````

When I serialize without any `:include`, then I get:

```json
    "relationships": {
        "otherThing": {
        }
    }
```

When I serialize with `include: 'otherThing'`, then I get:

```json
    "relationships": {
        "otherThing": {
            "type": "otherThings",   <--- I want this information
            "id": "123"              <--- and also this
        }
    }
"included": [    <--- But I don't need any of this
    {
        "type": "otherThings",
        "id": "123",
        "attributes": {},
        "links": {
            "self": "/otherThings/123"
        }
    }
]
```

Is there a way to get this middleground?

**Comment by hspazio** [comment]
@camjackson I've opened a [PR here](https://github.com/fotinakis/jsonapi-serializers/pull/44) that might be the middleground you are asking. It supports custom serializers for 'has_one' and 'has_many' relationships (rather than including the full list of attributes).

Perhaps something like this would work for you?

```ruby
# serializers/thing_serializer.rb
class ThingSerializer
  include JSONAPI::Serializer

  attribute :name

  has_many :other_things, serializer: OtherThingMinifiedSerializer
end

# serializers/other_thing_minified_serializer.rb
# this should not include any attributes BUT the resource will
# still appear in the 'included' section.
class OtherThingMinifiedSerializer
  include JSONAPI::Serializer
end
```

It's been queued for @fotinakis for review.

**Comment by camjackson** [comment]
@hspazio Ideally I'd like to exclude the resource from the `included` block altogether, as my primary reason for requesting this is for a particular resource that has no attributes (just an `id`).

I can think of four different levels of detail:

1. Don't even mention that the relationship is there at all
2. Mention that the relationship exists, but provide no further information about it
3. Provide the reference data for the relationship (i.e. id & type), so that it can be fetched later
4. As above, but also provide the full resource in the `included` section (along

To me, options 3 & 4 seem the most useful, but I could also see an argument for option 1 if you *really* don't care about the relationship, and it doesn't make sense to include it at all. 

However, I can't see how option 2 (which is the behaviour you currently get with no `:include` argument) would ever be useful? It's quite possible that I'm totally missing something though :)

But yeah, option 3 is what I really want, but I don't think it's possible at the moment.

All of that said, with a very general library like this if you give builtin options for every single possible use case, it can become a bit of a monster. So perhaps the custom serializer approach is a better one. Custom methods for things like `base_url` have been working very well for me so far.

**Comment by lucasm-iRonin** [comment]
Maybe some options provided to `has_one` / `has_many` could allow to enable / disable `data` for relationships no matter whether it's included or not?

**Comment by fotinakis** [comment]
@camjackson FYI, this is being worked on in https://github.com/fotinakis/jsonapi-serializers/pull/62
