### ISSUE TITLE
Intermediate resources should be returned in the include

### ISSUE THREAD

**Issue by jcarlos** [fotinakis/jsonapi-serializers#49]
Hello,

The spec for compound documents ( http://jsonapi.org/format/#document-structure-compound-documents ) says "[..]  intermediate resources in a multi-part path must be returned along with the leaf nodes. For example, a response to a request for comments.author should include comments as well as the author of each of those comments [...]".

The current implementation ( https://github.com/fotinakis/jsonapi-serializers/blob/1a1d122078662fb3b8710f3d11a23a305f285e71/spec/serializer_spec.rb#L543 ) returns only the final resource (e.g. only the author of ?include=comments.author instead of comments and comments.author.

Cheers,

**Comment by fotinakis** [comment]
Interesting! That must have changed in v1 and I didn't catch it. The old spec said the exact opposite:

> Note: A request for comments.author should not automatically also include comments in the response. This can happen if the client already has the comments locally, and now wants to fetch the associated authors without fetching the comments again.
- http://jsonapi-rc3.herokuapp.com/format/

I will not be able to get to this soon, maybe in the next few weeks. It should be very easy to update:

Around here:
https://github.com/fotinakis/jsonapi-serializers/blob/1a1d122078662fb3b8710f3d11a23a305f285e71/lib/jsonapi-serializers/serializer.rb#L473
```
data[current_level].merge!({_include: true})
```
...should be duplicated and added to the `Need to recurse more.` case, and then the tests updated.

**Comment by jcarlos** [comment]
I've tried to had a go on fixing it, please see if it makes sense: https://github.com/fotinakis/jsonapi-serializers/pull/50

**Comment by fotinakis** [comment]
Fixed by #50
