### ISSUE TITLE
Version 0.2.1 is on RubyGems, not on repo

### ISSUE THREAD

**Issue by mrcasals** [fotinakis/jsonapi-serializers#5]
Hi!

I see that version 0.2.1 is already [released on RubyGems](https://rubygems.org/gems/jsonapi-serializers), but not on `master` branch in the repo:

![](https://i.imgur.com/BJSWWdf.png)

Commit updating the version is 7d91633bb2cb5391b284249cb44e06bb76ee7696, which is on the `spec-updates` branch.

Can you officialy release this version?

**Comment by fotinakis** [comment]
Oh whoops, I accidentally pushed it to a branch instead of master. One sec...

**Comment by fotinakis** [comment]
Fixed, good catch.
