### ISSUE TITLE
Sparse Fieldsets

### ISSUE THREAD

**Issue by SeyZ** [fotinakis/jsonapi-serializers#56]
Hey @fotinakis 

According to the spec http://jsonapi.org/format/#fetching-sparse-fieldsets
Is it possible to configure dynamic attributes to serialize?

Thanks!

**Comment by fotinakis** [comment]
I'd love to support sparse fieldset handling but we don't have anything yet. You can sort of fake it with `context` support (which is incomplete, need to get https://github.com/fotinakis/jsonapi-serializers/pull/53/files in) by showing/hiding attributes based on context combined with an `if` or `unless`, like `attribute :post, if: :show_post?`. But, we should just support sparse fieldsets natively.

**Comment by fotinakis** [comment]
Supported now in 0.16.0 https://github.com/fotinakis/jsonapi-serializers#sparse-fieldsets
