### ISSUE TITLE
Using a serializer to restructure Hashes doesn't work because of `is_collection`

### ISSUE THREAD

**Issue by smackesey** [fotinakis/jsonapi-serializers#58]
I have an application where the data is passed around as plain Hashes. When it comes time to serve the data with JSON API, they need to be restructured. I would like to use `JSONAPI::Serializers` to do this. First I figure out what serializer to use by calling a function `get_serializer` on the hash. Then I call `JSONAPI::Serializer.serialize` and pass the `serializer` explicitly. It complains with `JSONAPI::Serializer::AmbiguousCollectionError`, presumably because `Hash`es are collections and I did not pass `is_collection: true`. I tried to get around this by passing it `is_collection: false` but it fails in the same way. My current workaround is to wrap my `Hash`es in proxy objects, but this is ugly. It seems like all that is needed is to have the code take me at my word on `is_collection: false` ...

```ruby
# `data` is a Hash
serializer = get_serializer(data)
JSONAPI::Serializers.serialize(data, serializer: serializer)  #=> AmbiguousCollectionError
JSONAPI::Serializers.serialize(data, serializer: serializer, is_collection: false)  #=> AmbiguousCollectionError
```

**Comment by fotinakis** [comment]
Try passing `skip_collection_check: true`.

**Comment by smackesey** [comment]
Thanks @fotinakis; your suggestion works. Unless I'm missing something though, the `:skip_collection_check` option seems unnecessary and unintuitive. Why not let `is_collection: false` play the same role? I'm looking at the code now, and it seems that the default value for `:is_collection` in `Serializer::serialize` could be set to `nil` or some symbol rather than `false`. Then, instead of:

    if !options[:skip_collection_check] && objects.respond_to?(:each)

You have:

    if options[:is_collection].nil? && objects.respond_to?(:each)

That is, you only perform the collection check when `:is_collection` is not passed explicitly. Of course, we wouldn't want to break backward compatibility by getting rid of `:skip_collection_check`. One could also internally set `:skip_collection_check` (maybe flagging it as deprecated) based on `:is_collection`.

If these ideas sound reasonable to you I'm happy to submit a PR.

**Comment by fotinakis** [comment]
Glad it works! The `skip_collection_check` was added by a contributor who had a different but related problem (that the `.respond_to?` duck-typing check would return true for their modeling system even on singular objects).

I prefer my booleans to be just booleans (truthy/falsey) and not "ternary booleans" (nil/true/false) for clarity, so let's keep things as is. Also I think treating `is_collection: false` as a special flag is not strong enough here and creates a lot of new ambiguity—the point of `is_collection` is that we will raise an `AmbiguousCollectionError` if it doesn't match what you then try to serialize, which we must do for JSON-API nil handling. So, the `skip_collection_check` is way more obvious flag to skip that than introducing special truthy handling.
