### ISSUE TITLE
Full Linkage Violation

### ISSUE THREAD

**Issue by smackesey** [fotinakis/jsonapi-serializers#61]
In `Serializer::find_recursive_relatioships`, a tree is built for `includes` which offers the possibility of not including intermediate resources. Quoting from a comment:

        # We only include parent values if the sential value _include is set. This satifies the
        # spec note: A request for comments.author should not automatically also include comments
        # in the response. This can happen if the client already has the comments locally, and now
        # wants to fetch the associated authors without fetching the comments again.
        # http://jsonapi.org/format/#fetching-includes

I checked the spec and I think this part is gone-- now "full linkage" is required, meaning that excluding intermediate resources is not allowed. As far as I can tell the public API does not offer a way to trigger the exclusion functionality, but having this in the codebase is nonetheless confusing since it's not up to date with the spec.

**Comment by fotinakis** [comment]
Are you on an old version of master? This has been fixed.

**Comment by fotinakis** [comment]
https://github.com/fotinakis/jsonapi-serializers/issues/49

**Comment by fotinakis** [comment]
Oh that comment is out of date, the behavior is correct.

**Comment by fotinakis** [comment]
Fixed the comment in https://github.com/fotinakis/jsonapi-serializers/commit/6d7804b88545414ca8912224ce83e7330107eb90
