### ISSUE TITLE
`serialize_errors` is throwing undefined method

### ISSUE THREAD

**Issue by mikeLspohn** [fotinakis/jsonapi-serializers#72]
I'm trying to serialize errors in a Rails project using `serialize_errors` but it keeps throwing this error:
    NoMethodError (undefined method `serialize_errors' for JSONAPI::Serializer:Module

Here's the controller action:

    if @participant.update(deserialize_params(participant_params))
      render json: serialize_model(@participant), status: :created
    else
      render json: JSONAPI::Serializer.serialize_errors(@participant.errors), status: :unprocessable_entity
    end

The regular `JSONAPI::Serializer.serialize` works fine for me, but serializing errors using the documentation isn't working for me.

Rails v4.2.6
Ruby v2.3.0

**Comment by fotinakis** [comment]
What version of jsonapi-serializers are you on? You need to be on the latest.

**Comment by fotinakis** [comment]
Closing as inactive, feel free to re-open.
