### ISSUE TITLE
Serialization for creation of new resources (POST)

### ISSUE THREAD

**Issue by doughsay** [fotinakis/jsonapi-serializers#75]
I'm a little confused about how to properly use this library to serialize payloads when creating new resources for a jsonapi compliant service.

1.) This library seems to assume that you need an id.  If id is nil, the library includes an empty string for the id in the payload.  The id field is not required when POSTing a new resource.  Is there a way I can get the id to not be included in the payload?

2.) It seems to always include the top level "self" link in the payload.  Although my server will just ignore this, it seems silly to include it when creating a new resource.  I can disable relationship links by using the "include_links" option, but is there a way to remove serialization of all links?

In general, how should one use this library to generate payloads for POSTing; has this been thought through any?

**Comment by fotinakis** [comment]
1) the `id` field is required by the spec for all serialized resource objects: http://jsonapi.org/format/#document-resource-objects — since this library focuses pretty exclusively on serialization and not deserialization, I think it's fine that we always include this right now.

2) See the last line of the https://github.com/fotinakis/jsonapi-serializers#more-customizations section for how to exclude self links.

So, in general, sounds like you're using this library client-side to make payloads that can be POSTed, which is not what it was primarily designed for.

**Comment by fotinakis** [comment]
We're primarily meant to go the other direction. :)

**Comment by doughsay** [comment]
Thanks for pointing me in the right direction for disabling the self links!

As to the other stuff, I really only see two use-cases with jsonapi: serialization and deserialization.  I understand exactly what you're trying to do: serialization for outgoing payloads in jsonapi services.  But you're so close to being able to solve the other use-case as well: serialization for POST / PATCH payloads to other jsonapi services.  Now that I know how to disable self links, the only thing "wrong" is that an empty id field gets included in the payload when the id is nil.  My server ignores the id field on POSTs right now anyway though, so it's not a big deal for me.  It's just so close to being perfect ;)

Anyway, thanks for the good work, it's still a really great library!

**Comment by doughsay** [comment]
Just to clarify as well though, directly from the docs link you included:

"Exception: The id member is not required when the resource object originates at the client and represents a new resource to be created on the server."

**Comment by fotinakis** [comment]
👍  I'd be happy to support exclusion of `id` for that case. We could do it explicitly with an `exclude_id: true` arg, or since it's blank right now and doesn't raise an error, we could do it implicitly by just adding some trailing `if !id.nil?` checks on the ID fields.
