### ISSUE TITLE
Remove automatic collection serialization

### ISSUE THREAD

**Issue by TiagoCardoso1983** [fotinakis/jsonapi-serializers#85]
This feature also breaks usage for the sequel ORM. Consider this check:

https://github.com/fotinakis/jsonapi-serializers/blob/0b4385cba9aac3c8b1ef822da11c8b80f4144492/lib/jsonapi-serializers/serializer.rb#L295-L301

`Sequel::Model` objects respond to `#each` although they're not collections. This is a needless check IMO. If I'm setting `is_collection: true`, I'm setting explicitly that it is a collection, and the same otherwise.

**Comment by fotinakis** [comment]
See https://github.com/fotinakis/jsonapi-serializers#sinatra-example  -- there is a `skip_collection_check` that does what you want.

**Comment by TiagoCardoso1983** [comment]
Yup, I am aware of the option, and am using it already. But is it right to assume collections on #each ? Because there is also a is_collection option. All my calls to the serialized have is_collection or skip_collection_check set to true, and it looks needless IMO
