### ISSUE TITLE
Best practice for creating secondary relationship?  

### ISSUE THREAD

**Issue by onewheelskyward** [fotinakis/jsonapi-serializers#89]
I'm doing something a little wonky, and I'd like an opinion as I dig into the code.  On my base object, I have a has_one relationship to a location, which works great.  I now want to have a second relationship, also to location, from that same object.  

`has_one :location` works terrifically, and now I'd like to add something like:

`has_one :location, key: :event_location_id` or something like that.  

I haven't found a way to do this yet, but I am messing about with the has_one block format which seems promising.  I thought I'd ask here for opinions on the matter.

Thank you!

**Comment by fotinakis** [comment]
This library works on types, not names, so you can just do `has_one :event_location` and if the event_location object is a Location, it will be serialized correctly.

**Comment by onewheelskyward** [comment]
Thanks @fotinakis!  I think I know how to pull that off.
