### ISSUE TITLE
No status code option on serialize_errors method?

### ISSUE THREAD

**Issue by mellogarrett** [fotinakis/jsonapi-serializers#97]
Is there a way to specify the status code on this method? Or does it only let you pass in objects to the `errors` array

**Comment by mwpastore** [comment]
No, you can only pass in objects, specifically an array of error hashes. I usually do something like this:

```ruby
JSONAPI::Serializer.serialize_errors([
  {
    id: SecureRandom.uuid,
    title: "foo",
    detail: "bar",
    status: response.status.to_s # or your framework's equivalent
  }
])
```

Assuming the response status is already set. If it's not, you can use the same value to set the response status and populate the error hash.

**Comment by mellogarrett** [comment]
That's weird having the status codes nested. The browser doesn't react to the response like I would expect. It gets status code 200, even if the response comes back like so:

    {"errors"=>[{:status=>401, :title=>"Unauthorized", :detail=>"The username and password combination you entered is not valid."}]}```

**Comment by mwpastore** [comment]
If you want to set the status code of the response, you have to set it. The browser won't automagically extract it out of the payload. For example, in Sinatra you would say `status 401` and `body JSONAPI::Serializer.serialize_errors(..`. 

It's optional to set the status in the payload. It really depends on what's consuming the {json:api}. Some things use the response status, some things use the status in the payload, some things will intelligently use both. It's useful for when a request generates multiple errors: you can return a generic 400 response with detailed 403, 404, 409, 415, etc. errors in the payload.

**Comment by mellogarrett** [comment]
Gotcha. Thanks for the quick help!
